// fields_and_descriptions.js
// This file defines the segmentDescriptions and fieldDescriptions objects for HL7 parsing.
// Attach them to the global window object so they are available in browser/Babel JSX scripts.

window.segmentDescriptions = {
  MSH: 'Message Header',
  SFT: 'Software Segment',
  MSA: 'Message Acknowledgment',
  ERR: 'Error',
  EVN: 'Event Type',
  PID: 'Patient Identification',
  PD1: 'Patient Additional Demographic',
  NK1: 'Next of Kin / Associated Parties',
  PV1: 'Patient Visit',
  PV2: 'Patient Visit - Additional Information',
  MRG: 'Merge Patient Information',
  ORC: 'Common Order',
  TQ1: 'Timing/Quantity',
  TQ2: 'Timing/Quantity Relationship',
  OBR: 'Observation Request',
  SPM: 'Specimen',
  OBX: 'Observation/Result',
  NTE: 'Notes and Comments',
  AL1: 'Patient Allergy Information',
  DG1: 'Diagnosis',
  PR1: 'Procedures',
  GT1: 'Guarantor',
  IN1: 'Insurance',
  IN2: 'Insurance Additional Information',
  RXO: 'Pharmacy/Treatment Order',
  RXE: 'Pharmacy/Treatment Encoded Order',
  RXC: 'Pharmacy/Treatment Component',
  RXA: 'Pharmacy/Treatment Administration',
  RXR: 'Pharmacy/Treatment Route',
  TXA: 'Transcription Document Header',
  FT1: 'Financial Transaction',
  ACC: 'Accident',
  UB1: 'UB82',
  UB2: 'UB92 Data',
  ZCF: 'Custom Segment',
};

window.fieldDescriptions = {
  // Header and Acknowledgment
  MSH: ['Field Separator','Encoding Characters','Sending Application','Sending Facility','Receiving Application','Receiving Facility','Date/Time of Message','Security','Message Type','Message Control ID','Processing ID','Version ID','Sequence Number','Continuation Pointer','Accept Acknowledgment Type','Application Acknowledgment Type','Country Code','Character Set','Principal Language Of Message','Alternate Character Set Handling Scheme','Message Profile Identifier'],
  SFT: ['Software Vendor Organization','Software Certified Version or Release Number','Software Product Name','Software Binary ID','Software Product Information','Software Install Date'],
  MSA: ['Acknowledgment Code','Message Control ID','Text Message','Expected Sequence Number','Delayed Acknowledgment Type','Error Condition','Message Waiting Number','Message Waiting Priority'],
  ERR: ['Error Code and Location','HL7 Error Code','Severity','Application Error Code','Application Error Parameter','Diagnostic Information','User Message','Inform Person Indicator','Override Type','Override Reason Code','Help Desk Contact Point'],

  // Event and Patient
  EVN: ['Event Type Code','Recorded Date/Time','Date/Time Planned Event','Event Reason Code','Operator ID','Event Occurred','Event Facility'],
  PID: ['Set ID','Patient ID','Patient Identifier List','Alternate Patient ID','Patient Name','Mother\'s Maiden Name','Date/Time of Birth','Administrative Sex','Patient Alias','Race','Patient Address','County Code','Phone Number - Home','Phone Number - Business','Primary Language','Marital Status','Religion','Patient Account Number','SSN Number','Driver\'s License Number','Mother\'s Identifier','Ethnic Group','Birth Place','Multiple Birth Indicator','Birth Order','Citizenship','Veterans Military Status','Nationality','Patient Death Date and Time','Patient Death Indicator','Identity Unknown Indicator','Identity Reliability Code','Last Update Date/Time','Last Update Facility','Species Code','Breed Code','Strain','Production Class Code','Tribal Citizenship'],
  PD1: ['Living Dependency','Living Arrangement','Patient Primary Facility','Patient Primary Care Provider Name','Student Indicator','Handicap','Living Will Code','Organ Donor Code','Separate Bill','Duplicate Patient','Publicity Code','Protection Indicator','Protection Indicator Effective Date','Place of Worship','Advance Directive Code','Immunization Registry Status','Immunization Registry Status Effective Date','Publicity Code Effective Date','Military Branch','Military Rank/Grade','Military Status'],
  NK1: ['Set ID','Name','Relationship','Address','Phone Number','Business Phone Number','Contact Role','Start Date','End Date','Next of Kin / Associated Parties Job Title','Next of Kin / Associated Parties Job Code/Class','Next of Kin / Associated Parties Employee Number','Organization Name','Marital Status','Administrative Sex','Date/Time of Birth','Living Dependency','Ambulatory Status','Citizenship','Primary Language','Living Arrangement','Publicity Code','Protection Indicator','Student Indicator','Religion','Mother\'s Maiden Name','Nationality','Ethnic Group','Contact Reason','Contact Person\'s Name','Contact Person\'s Telephone Number','Contact Person\'s Address','Next of Kin/Associated Party\'s Identifiers','Job Status','Race','Handicap','Contact Person Social Security Number','Next of Kin Birth Place','VIP Indicator'],
  PV1: ['Set ID','Patient Class','Assigned Patient Location','Admission Type','Preadmit Number','Prior Patient Location','Attending Doctor','Referring Doctor','Consulting Doctor','Hospital Service','Temporary Location','Preadmit Test Indicator','Readmission Indicator','Admit Source','Ambulatory Status','VIP Indicator','Admitting Doctor','Patient Type','Visit Number','Financial Class','Charge Price Indicator','Courtesy Code','Credit Rating','Contract Code','Contract Effective Date','Contract Amount','Contract Period','Interest Code','Transfer to Bad Debt Code','Transfer to Bad Debt Date','Bad Debt Agency Code','Bad Debt Transfer Amount','Bad Debt Recovery Amount','Delete Account Indicator','Delete Account Date','Discharge Disposition','Discharged to Location','Diet Type','Servicing Facility','Bed Status','Account Status','Pending Location','Prior Temporary Location','Admit Date/Time','Discharge Date/Time','Current Patient Balance','Total Charges','Total Adjustments','Total Payments','Alternate Visit ID','Visit Indicator','Other Healthcare Provider'],
  PV2: ['Prior Pending Location','Accommodation Code','Admit Reason','Transfer Reason','Patient Valuables','Patient Valuables Location','Visit User Code','Expected Admit Date/Time','Expected Discharge Date/Time','Estimated Length of Inpatient Stay','Actual Length of Inpatient Stay','Visit Description','Referral Source Code','Previous Service Date','Employment Illness Related Indicator','Purge Status Code','Purge Status Date','Special Program Code','Retention Indicator','Expected Number of Insurance Plans','Visit Publicity Code','Visit Protection Indicator','Clinic Organization Name','Patient Status Code','Visit Priority Code','Previous Treatment Date','Expected Discharge Disposition','Signature on File Date','First Similar Illness Date','Patient Charge Adjustment Code','Recurring Service Code','Billing Media Code','Expected Surgery Date and Time','Military Partnership Code','Military Non-Availability Code','Newborn Baby Indicator','Baby Detained Indicator','Mode of Arrival Code','Recreational Drug Use Code','Admission Level of Care Code','Precaution Code','Patient Condition Code','Living Will Code','Organ Donor Code','Advance Directive Code','Patient Status Effective Date','Expected LOA Return Date/Time','Expected Pre-admission Testing Date/Time','Notify Clergy Code'],
  MRG: ['Prior Patient Identifier List','Prior Alternate Patient ID','Prior Patient Account Number','Prior Patient ID','Prior Visit Number','Prior Alternate Visit ID','Prior Patient Name'],

  // Orders and Timing
  ORC: ['Order Control','Placer Order Number','Filler Order Number','Placer Group Number','Order Status','Response Flag','Quantity/Timing','Parent Order','Date/Time of Transaction','Entered By','Verified By','Ordering Provider','Enterer\'s Location','Call Back Phone Number','Order Effective Date/Time','Order Control Code Reason','Entering Organization','Entering Device','Action By','Advanced Beneficiary Notice Code','Ordering Facility Name','Ordering Facility Address','Ordering Facility Phone Number','Ordering Provider Address','Order Status Modifier','Advanced Beneficiary Notice Override Reason','Filler\'s Expected Availability Date/Time','Confidentiality Code','Order Type','Enterer Authorization Mode'],
  TQ1: ['Set ID','Quantity','Repeat Pattern','Explicit Time','Relative Time and Units','Service Duration','Start Date/Time','End Date/Time','Priority','Condition Text','Text Instruction','Conjunction','Occurrence Duration','Total Occurrences'],
  TQ2: ['Set ID','Sequence/Results Flag','Related Placer Number','Related Filler Number','Related Placer Group Number','Sequence Condition Code','Cyclic Entry/Exit Indicator','Sequence Condition Time Interval','Cyclic Group Maximum Number of Repeats','Special Service Request Relationship'],

  // Observation Request and Results
  OBR: ['Set ID','Placer Order Number','Filler Order Number','Universal Service Identifier','Priority','Requested Date/Time','Observation Date/Time','Observation End Date/Time','Collection Volume','Collector Identifier','Specimen Action Code','Danger Code','Relevant Clinical Information','Specimen Received Date/Time','Specimen Source','Ordering Provider','Order Callback Phone Number','Placer Field 1','Placer Field 2','Filler Field 1','Filler Field 2','Results Rpt/Status Chng - Date/Time','Charge to Practice','Diagnostic Serv Sect ID','Result Status','Parent Result','Quantity/Timing','Result Copies To','Parent','Transportation Mode','Reason for Study','Principal Result Interpreter','Assistant Result Interpreter','Technician','Transcriptionist','Scheduled Date/Time','Number of Sample Containers','Transport Logistics of Collected Sample','Collector\'s Comment','Transport Arrangement Responsibility','Transport Arranged','Escort Required','Planned Patient Transport Comment','Procedure Code','Procedure Code Modifier','Placer Supplemental Service Information','Filler Supplemental Service Information','Medically Necessary Duplicate Procedure Reason','Result Handling','Parent Universal Service Identifier'],
  SPM: ['Set ID','Specimen ID','Specimen Parent IDs','Specimen Type','Specimen Type Modifier','Specimen Additives','Specimen Collection Method','Specimen Source Site','Specimen Source Site Modifier','Specimen Collection Site','Specimen Role','Specimen Collection Amount','Grouped Specimen Count','Specimen Description','Specimen Handling Code','Specimen Risk Code','Specimen Collection Date/Time','Specimen Received Date/Time','Specimen Expiration Date/Time','Specimen Availability','Specimen Reject Reason','Specimen Quality','Specimen Appropriateness','Specimen Condition','Specimen Current Quantity','Number of Specimen Containers','Container Type','Container Condition','Specimen Child Role'],
  OBX: ['Set ID','Value Type','Observation Identifier','Observation Sub-ID','Observation Value','Units','References Range','Abnormal Flags','Probability','Nature of Abnormal Test','Observation Result Status','Effective Date of Reference Range','User Defined Access Checks','Date/Time of the Observation','Producer\'s ID','Responsible Observer','Observation Method','Equipment Instance Identifier','Date/Time of the Analysis'],
  NTE: ['Set ID','Source of Comment','Comment','Comment Type'],

  // Allergies, Diagnoses, Procedures, Financial
  AL1: ['Set ID','Allergen Type Code','Allergen Code/Mnemonic/Description','Allergy Severity Code','Allergy Reaction Code','Identification Date'],
  DG1: ['Set ID','Diagnosis Coding Method','Diagnosis Code','Diagnosis Description','Diagnosis Date/Time','Diagnosis Type','Major Diagnostic Category','Diagnostic Related Group','DRG Approval Indicator','DRG Grouper Review Code','Outlier Type','Outlier Days','Outlier Cost','Grouper Version And Type','Diagnosis Priority','Diagnosing Clinician','Diagnosis Classification','Confidential Indicator','Attestation Date/Time','Diagnosis Identifier','Diagnosis Action Code'],
  PR1: ['Set ID','Procedure Coding Method','Procedure Code','Procedure Description','Procedure Date/Time','Procedure Functional Type','Procedure Minutes','Anesthesiologist','Anesthesia Code','Anesthesia Minutes','Surgeon','Procedure Practitioner','Consent Code','Procedure Priority','Associated Diagnosis Code','Procedure Code Modifier','Procedure DRG Type','Tissue Type Code','Procedure Identifier','Procedure Action Code'],
  FT1: ['Set ID','Transaction ID','Transaction Batch ID','Transaction Date','Transaction Posting Date','Transaction Type','Transaction Code','Transaction Description','Transaction Description - Alt','Transaction Quantity','Transaction Amount - Extended','Transaction Amount - Unit','Department Code','Insurance Plan ID','Insurance Amount','Assigned Patient Location','Fee Schedule','Patient Type','Diagnosis Code - FT1','Performed By Code','Ordered By Code','Unit Cost','Filler Order Number','Entered By Code','Procedure Code','Procedure Code Modifier','Advanced Beneficiary Notice Code','Medically Necessary Duplicate Procedure Reason','NDC Code','Payment Reference ID','Transaction Reference Key'],
  ACC: ['Accident Date/Time','Accident Code','Accident Location','Auto Accident State','Accident Job Related Indicator','Accident Death Indicator','Entered By','Accident Description','Brought In By','Police Notified Indicator','Accident Address'],

  // Guarantor / Insurance
  GT1: ['Set ID','Guarantor Number','Guarantor Name','Guarantor Spouse Name','Guarantor Address','Guarantor Phone Number - Home','Guarantor Phone Number - Business','Guarantor Date/Time Of Birth','Guarantor Administrative Sex','Guarantor Type','Guarantor Relationship','Guarantor SSN','Guarantor Date - Begin','Guarantor Date - End','Guarantor Priority','Guarantor Employer Name','Guarantor Employer Address','Guarantor Employer Phone Number','Guarantor Employee ID Number','Guarantor Employment Status','Guarantor Organization Name','Guarantor Billing Hold Flag','Guarantor Credit Rating Code','Guarantor Death Date And Time','Guarantor Death Flag','Guarantor Charge Adjustment Code','Guarantor Household Annual Income','Guarantor Household Size','Guarantor Employer ID Number','Guarantor Marital Status Code','Guarantor Hire Effective Date','Employment Stop Date','Living Dependency','Ambulatory Status','Citizenship','Primary Language','Living Arrangement','Publicity Code','Protection Indicator','Student Indicator','Religion','Mother\'s Maiden Name','Nationality','Ethnic Group','Contact Person\'s Name','Contact Person\'s Telephone Number','Contact Reason','Contact Relationship','Job Title','Job Code/Class','Guarantor Employer\'s Organization Name','Handicap','Job Status','Guarantor Financial Class','Guarantor Race','Guarantor Birth Place','VIP Indicator'],
  IN1: ['Set ID','Insurance Plan ID','Insurance Company ID','Insurance Company Name','Insurance Company Address','Insurance Co Contact Person','Insurance Co Phone Number','Group Number','Group Name','Insured\'s Group Emp ID','Insured\'s Group Emp Name','Plan Effective Date','Plan Expiration Date','Authorization Information','Plan Type','Name Of Insured','Insured\'s Relationship To Patient','Insured\'s Date Of Birth','Insured\'s Address','Assignment Of Benefits','Coordination Of Benefits','Coord Of Ben. Priority','Notice Of Admission Flag','Notice Of Admission Date','Report Of Eligibility Flag','Report Of Eligibility Date','Release Information Code','Pre-Admit Cert','Verification Date/Time','Verification By','Type Of Agreement Code','Billing Status','Lifetime Reserve Days','Delay Before L.R. Day','Company Plan Code','Policy Number','Policy Deductible','Policy Limit - Amount','Policy Limit - Days','Room Rate - Semi-Private','Room Rate - Private','Insured\'s Employment Status','Insured\'s Administrative Sex','Insured\'s Employer\'s Address','Verification Status','Prior Insurance Plan ID','Coverage Type','Handicap','Insured\'s ID Number','Signature Code','Signature Code Date','Insured\'s Birth Place','VIP Indicator'],
  IN2: ['Insured\'s Employee ID','Insured\'s Social Security Number','Insured\'s Employer\'s Name and ID','Employer Information Data','Mail Claim Party','Medicare Health Ins Card Number','Medicaid Case Name','Medicaid Case Number','Military Sponsor Name','Military ID Number','Dependent Of Military Recipient','Military Organization','Military Station','Military Service','Military Rank/Grade','Military Status','Military Retire Date','Military Non-Avail Cert On File','Baby Coverage','Combine Baby Bill','Blood Deductible','Special Coverage Approval Name','Special Coverage Approval Title','Non-Covered Insurance Code','Payor ID','Payor Subscriber ID','Eligibility Source','Room Coverage Type/Amount','Policy Type/Amount','Daily Deductible','Living Dependency','Ambulatory Status','Citizenship','Primary Language','Living Arrangement','Publicity Code','Protection Indicator','Student Indicator','Religion','Mother\'s Maiden Name','Nationality','Ethnic Group','Marital Status','Insured\'s Employment Start Date','Employment Stop Date','Job Title','Job Code/Class','Job Status','Employer Contact Person Name','Employer Contact Person Phone Number','Employer Contact Reason','Insured\'s Contact Person\'s Name','Insured\'s Contact Person Phone Number','Insured\'s Contact Person Reason','Relationship To The Patient Start Date','Relationship To The Patient Stop Date','Insurance Co. Contact Reason','Insurance Co Contact Phone Number','Policy Scope','Policy Source','Patient Member Number','Guarantor\'s Relationship To Insured','Insured\'s Phone Number - Home','Insured\'s Employer Phone Number','Military Handicapped Program','Suspend Flag','Copay Limit Flag','Stoploss Limit Flag','Insured Organization Name And ID','Insured Employer Organization Name And ID','Race','HCFA Patient\'s Relationship to Insured'],

  // Pharmacy (Orders/Encoded/Component/Admin/Route)
  RXO: ['Requested Give Code','Requested Give Amount - Minimum','Requested Give Amount - Maximum','Requested Give Units','Requested Dosage Form','Provider\'s Pharmacy/Treatment Instructions','Provider\'s Administration Instructions','Deliver-To Location','Allow Substitutions','Requested Dispense Code','Requested Dispense Amount','Requested Dispense Units','Number Of Refills','Ordering Provider\'s DEA Number','Pharmacist/Treatment Supplier\'s Verifier ID','Needs Human Review','Requested Give Per (Time Unit)','Requested Give Strength','Requested Give Strength Units','Indication','Requested Give Rate Amount','Requested Give Rate Units','Total Daily Dose','Supplementary Code','Requested Drug Strength Volume','Requested Drug Strength Volume Units','Pharmacy Order Type'],
  // Added the most commonly used and positionally correct initial fields for RXE (2.5.1).
  RXE: ['Give Code','Give Amount - Minimum','Give Amount - Maximum','Give Units','Give Dosage Form','Provider\'s Administration Instructions','Deliver-To Location','Substitution Status','Dispense Amount','Dispense Units','Number Of Refills','Ordering Provider\'s DEA Number','Pharmacist/Treatment Supplier\'s Verifier ID','Prescription Number'],
  RXC: ['RX Component Type','Component Code','Component Amount','Component Units','Component Strength','Component Strength Units','Supplementary Code','Component Drug Strength Volume','Component Drug Strength Volume Units'],
  RXA: ['Give Sub-ID Counter','Administration Sub-ID Counter','Date/Time Start of Administration','Date/Time End of Administration','Administered Code','Administered Amount','Administered Units','Administered Dosage Form','Administration Notes','Administering Provider','Administered-at Location','Administered Per (Time Unit)','Administered Strength','Administered Strength Units','Substance Lot Number','Substance Expiration Date','Substance Manufacturer Name','Substance/Treatment Refusal Reason','Indication','Completion Status','Action Code - RXA','System Entry Date/Time','Administered Drug Strength Volume','Administered Drug Strength Volume Units','Administered Barcode Identifier','Pharmacy Order Type'],
  RXR: ['Route','Administration Site','Administration Device','Administration Method','Routing Instruction'],

  // Documentation
  TXA: ['Set ID','Document Type','Document Content Presentation','Activity Date/Time','Primary Activity Provider Code/Name','Origination Date/Time','Transcription Date/Time','Edit Date/Time','Originator Code/Name','Assigned Document Authenticator','Transcriptionist Code/Name','Unique Document Number','Parent Document Number','Placer Order Number','Filler Order Number','Unique Document File Name','Document Completion Status','Document Confidentiality Status','Document Availability Status','Document Storage Status','Document Change Reason','Authentication Person, Time Stamp','Distributed Copies'],

  // UB segments (legacy billing)
  UB1: ['Set ID','Blood Deductible','Blood Furnished-Pints','Blood Replaced-Pints','Blood Not Replaced-Pints','Co-Insurance Days','Condition Code','Covered Days','Non Covered Days','Value Amount & Code','Number Of Grace Days','Special Program Indicator','PSRO/UR Approval Indicator','PSRO/UR Approved Stay-Fm','PSRO/UR Approved Stay-To','Occurrence','Occurrence Span','Occur Span Start Date','Occur Span End Date','UB-82 Locator 2','UB-82 Locator 9','UB-82 Locator 27','UB-82 Locator 45'],
  UB2: ['Set ID','Co-Insurance Days','Condition Code','Covered Days','Non-Covered Days','Value Amount & Code','Occurrence Code & Date','Occurrence Span Code/Dates','Uniform Billing Locator 2 (State)','Uniform Billing Locator 11 (State)','Uniform Billing Locator 31 (National)','Document Control Number','Uniform Billing Locator 49 (National)','Uniform Billing Locator 56 (State)','Uniform Billing Locator 57 (National)','Uniform Billing Locator 78 (State)','Special Visit Count'],
};
